# Generated by Django 5.0.2 on 2024-02-19 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_2_app', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images'),
        ),
    ]
