# Generated by Django 5.0.2 on 2024-02-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='public_flag',
            field=models.BooleanField(default=True),
        ),
    ]
